---
kafka:
  broker: "localhost:9092"
log:
  level: "debug"
server:
  port: :8081
  cors: true
  ginMode: "debug"
  debug: false
email:
  server: "smtp.gmail.com:587"
  account: "gitlab@ubiik.com"
  password: ""
  accountName: "DER-EMS Mailer"
  plainAuth: true
db:
  derems:
    driver: mysql
    connection: "ubiik:testing123@tcp(0.0.0.0:3306)/ems_dev?parseTime=true"
