---
log:
  level: "debug"
server:
  port: :8081
  cors: true
  ginMode: "debug"
  debug: true
db:
  derems:
    driver: mysql
    connection: "ubiik:testing123@tcp(0.0.0.0:3306)/der_ems?parseTime=true"
