// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package deremsmodels

var TableNames = struct {
	CustomerInfo    string
	Device          string
	DeviceModel     string
	Gateway         string
	WeatherForecast string
}{
	CustomerInfo:    "customer_info",
	Device:          "device",
	DeviceModel:     "device_model",
	Gateway:         "gateway",
	WeatherForecast: "weather_forecast",
}
