// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package deremsmodels

var TableNames = struct {
	CCData           string
	CCDataLog        string
	Customer         string
	Device           string
	DeviceModel      string
	Gateway          string
	LoginLog         string
	Tou              string
	TouHoliday       string
	TouLocation      string
	User             string
	UserGatewayRight string
	WeatherForecast  string
}{
	CCData:           "cc_data",
	CCDataLog:        "cc_data_log",
	Customer:         "customer",
	Device:           "device",
	DeviceModel:      "device_model",
	Gateway:          "gateway",
	LoginLog:         "login_log",
	Tou:              "tou",
	TouHoliday:       "tou_holiday",
	TouLocation:      "tou_location",
	User:             "user",
	UserGatewayRight: "user_gateway_right",
	WeatherForecast:  "weather_forecast",
}
