// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package deremsmodels

var TableNames = struct {
	AiData                     string
	CCData                     string
	CCDataLog                  string
	CCDataLogCalculatedDaily   string
	CCDataLogCalculatedMonthly string
	Device                     string
	DeviceLog                  string
	DeviceModel                string
	DeviceModule               string
	Gateway                    string
	GatewayLog                 string
	Group                      string
	GroupGatewayRight          string
	GroupGatewayRightLog       string
	GroupType                  string
	GroupTypeWebpageRight      string
	Location                   string
	LoginLog                   string
	PowerOutagePeriod          string
	Tou                        string
	TouHoliday                 string
	TouLocation                string
	User                       string
	WeatherForecast            string
	Webpage                    string
}{
	AiData:                     "ai_data",
	CCData:                     "cc_data",
	CCDataLog:                  "cc_data_log",
	CCDataLogCalculatedDaily:   "cc_data_log_calculated_daily",
	CCDataLogCalculatedMonthly: "cc_data_log_calculated_monthly",
	Device:                     "device",
	DeviceLog:                  "device_log",
	DeviceModel:                "device_model",
	DeviceModule:               "device_module",
	Gateway:                    "gateway",
	GatewayLog:                 "gateway_log",
	Group:                      "group",
	GroupGatewayRight:          "group_gateway_right",
	GroupGatewayRightLog:       "group_gateway_right_log",
	GroupType:                  "group_type",
	GroupTypeWebpageRight:      "group_type_webpage_right",
	Location:                   "location",
	LoginLog:                   "login_log",
	PowerOutagePeriod:          "power_outage_period",
	Tou:                        "tou",
	TouHoliday:                 "tou_holiday",
	TouLocation:                "tou_location",
	User:                       "user",
	WeatherForecast:            "weather_forecast",
	Webpage:                    "webpage",
}
